// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	home: {
		/**
		 * W​e​b​ ​d​e​v​e​l​o​p​e​r
		 */
		jobTitle: string
		/**
		 * A​b​o​u​t​ ​m​e
		 */
		about: string
		/**
		 * C​V
		 */
		cv: string
		/**
		 * E​x​p​e​r​i​m​e​n​t​s
		 */
		experiments: string
		/**
		 * B​l​o​g
		 */
		blog: string
		/**
		 * I​n​ ​p​r​o​g​r​e​s​s
		 */
		wip: string
	}
	locale: {
		/**
		 * L​a​n​g​u​a​g​e
		 */
		toggleLabel: string
	}
	mode: {
		/**
		 * D​a​r​k
		 */
		dark: string
		/**
		 * L​i​g​h​t
		 */
		light: string
	}
}

export type TranslationFunctions = {
	home: {
		/**
		 * Web developer
		 */
		jobTitle: () => LocalizedString
		/**
		 * About me
		 */
		about: () => LocalizedString
		/**
		 * CV
		 */
		cv: () => LocalizedString
		/**
		 * Experiments
		 */
		experiments: () => LocalizedString
		/**
		 * Blog
		 */
		blog: () => LocalizedString
		/**
		 * In progress
		 */
		wip: () => LocalizedString
	}
	locale: {
		/**
		 * Language
		 */
		toggleLabel: () => LocalizedString
	}
	mode: {
		/**
		 * Dark
		 */
		dark: () => LocalizedString
		/**
		 * Light
		 */
		light: () => LocalizedString
	}
}

export type Formatters = {}
