name: FTP Deploy

on:
  push:
    branches: [ master ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: NPM Install
      run: npm ci --force

    - name: NPM Build
      run: npm run build
      env:
        NODE_ENV: production
        ADAPTER: static

    - name: FTP Deploy
      uses: marcodallasanta/ssh-scp-deploy@v1.0.4
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        local: "./build/"
        remote: "/terry/site"
        scp_options: -v
