name: FTP Deploy

on:
  push:
    branches: [ master ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    - name: NPM Install
      run: npm install

    - name: NPM Build
      run: npm run build
      env:
        NODE_ENV: production
        ADAPTER: static

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://home320321753.1and1-data.host/terry/site
        ftp-username: u57888140-terry
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build
        git-ftp-args: --insecure
